words:
  - alka
  - clsx
  - eatwise
  - oklch
  - shadcn
  - SMIL
  - SVGSVGElement
  - turbopack
  - vaul
  - vercel
  - WCAG
ignorePaths:
  - node_modules
  - pnpm-lock.yaml
  - cspell.config.yaml
  - .next
