# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: Setup Project
description: Setup Node.js, enable corepack and install dependencies

inputs:
  node-version:
    description: Node.js version
    required: false
    default: '22.x'
  pnpm-version:
    description: pnpm version
    required: false
    default: '10.5.2'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      name: Install global pnpm
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - name: Enable corepack
      run: corepack enable
      shell: bash
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
